### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by usurniro** [lsds/Crossbow#1]
From build.log:
+++++++++++++++++++++++++++++++++++++++++++++++++
[ERROR] /home/florin/Crossbow/src/main/java/uk/ac/imperial/lsds/crossbow/kernel/Accuracy.java:[8,41] package uk.ac.imperial.lsds.crossbow.data does not exist
[ERROR] /home/florin/Crossbow/src/main/java/uk/ac/imperial/lsds/crossbow/kernel/Kernel.java:[6,41] package uk.ac.imperial.lsds.crossbow.data does not exist
+++++++++++++++++++++++++++++++++++++++++++++++++
There is no "uk.ac.imperial.lsds.crossbow.data" folder in the git repo. Code is clearly missing.

**Comment by alexandroskoliousis** [comment]
Missing files added.
